name: 'Zoocha CKE5 Recipe'
description: 'Installs Zoocha CKE5 module and baseline configurations.'
type: 'Feature'

install:
  - ckeditor5
  - editor_advanced_link
  - ckeditor5_plugin_pack
  - ckeditor5_plugin_pack_find_and_replace
  - ckeditor5_premium_features_fullscreen
  - ckeditor5_plugin_pack_highlight
  - ckeditor5_plugin_pack_link_attributes
  - ckeditor5_plugin_pack_page_break
  - ckeditor5_plugin_pack_templates
  - ckeditor5_plugin_pack_word_count
config:
  # Allow config import to continue if config already exists.
  strict: false